name: "release"

on:
  push:
    tags:
      - "*"

env:
  DFX_VERSION: "0.14.1"

permissions:
  contents: write

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Install DFX
        run: |
          wget --output-document install-dfx.sh "https://internetcomputer.org/install.sh"
          bash install-dfx.sh < <(yes Y)
          rm install-dfx.sh
          dfx cache install
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Build canister
        run: |
          dfx build --network ic

      - name: Release
        uses: "softprops/action-gh-release@v1"
        with:
          files: Release.txt
